#!/bin/bash

# Generate models report from CPA-X API
# Fetches /v1/models and outputs formatted markdown

OUTPUT_DIR="."
OUTPUT_FILE="${OUTPUT_DIR}/report-models.md"
API_ENDPOINT="http://127.0.0.1:8317/v1/models"
CONFIG_FILE="/home/raven/.cli-proxy-api/config.yaml"
TIMESTAMP=$(date -Iseconds)

# Extract client API key from config (first entry under api-keys)
if [ -f "$CONFIG_FILE" ]; then
    # Extract the first api-key entry (OpenAI-compatible client key)
    API_KEY=$(grep -A 10 'api-keys:' "$CONFIG_FILE" | grep -E '^\s*-\s*sk-' | head -1 | sed -E 's/^\s*-\s*//')
    if [ -z "$API_KEY" ]; then
        API_KEY="dashboard-key-2026"  # fallback to management key
    fi
else
    API_KEY="dashboard-key-2026"
fi

echo "# CPA-X Models Report" > "$OUTPUT_FILE"
echo "Generated: $TIMESTAMP" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Fetch models data
if [ -n "$API_KEY" ]; then
    response=$(curl -s -H "Authorization: Bearer $API_KEY" "$API_ENDPOINT") || {
        echo "Error: Failed to fetch models from $API_ENDPOINT" >> "$OUTPUT_FILE"
        echo "cURL error: $?" >> "$OUTPUT_FILE"
        exit 1
    }
else
    response=$(curl -s "$API_ENDPOINT") || {
        echo "Error: Failed to fetch models from $API_ENDPOINT" >> "$OUTPUT_FILE"
        echo "cURL error: $?" >> "$OUTPUT_FILE"
        exit 1
    }
fi

# Check if response is valid JSON
if ! echo "$response" | jq empty 2>/dev/null; then
    echo "Error: Invalid JSON response from API" >> "$OUTPUT_FILE"
    echo "Raw response: $response" >> "$OUTPUT_FILE"
    exit 1
fi

# Extract models array (response uses .data)
models=$(echo "$response" | jq -r '.data // []')
model_count=$(echo "$models" | jq 'length')

echo "**Total Models:** $model_count" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "## Model List" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

if [ "$model_count" -eq 0 ]; then
    echo "No models available." >> "$OUTPUT_FILE"
    exit 0
fi

# Table header
echo "| ID | Provider | Created |" >> "$OUTPUT_FILE"
echo "|----|----------|---------|" >> "$OUTPUT_FILE"

# Iterate through models and format rows with jq (convert timestamp to date)
echo "$models" | jq -r '.[] | "| \(.id // "N/A") | \(.owned_by // "N/A") | \(.created // 0 | tostring | strptime("%s") | strftime("%Y-%m-%d %H:%M:%S")) |"' >> "$OUTPUT_FILE"

echo "" >> "$OUTPUT_FILE"
echo "*Report generated by report-models.sh*" >> "$OUTPUT_FILE"

echo "Report generated: $OUTPUT_FILE"
exit 0
