#!/bin/bash
# Generate models report from CPA-X API
# Fetches /v1/models and outputs formatted markdown
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/cpa-common.sh"

OUTPUT_FILE="${SCRIPT_DIR}/report-models.md"
TIMESTAMP=$(date -Iseconds)
API_URL=$(cpa_api_url "/v1/models")
API_KEY=$(cpa_first_api_key)

echo "# CPA-X Models Report" > "$OUTPUT_FILE"
echo "Generated: $TIMESTAMP" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Fetch models data
if [ -n "$API_KEY" ] && [ "$API_KEY" != "dashboard-key-2026" ]; then
    response=$(curl -sS -H "Authorization: Bearer $API_KEY" "$API_URL") || {
        echo "Error: Failed to fetch models from $API_URL" >> "$OUTPUT_FILE"
        echo "cURL exit code: $?" >> "$OUTPUT_FILE"
        exit 1
    }
else
    response=$(curl -sS "$API_URL") || {
        echo "Error: Failed to fetch models from $API_URL" >> "$OUTPUT_FILE"
        echo "cURL exit code: $?" >> "$OUTPUT_FILE"
        exit 1
    }
fi

# Check if response is valid JSON
if ! echo "$response" | jq empty 2>/dev/null; then
    echo "Error: Invalid JSON response from API" >> "$OUTPUT_FILE"
    echo "Raw response: $response" >> "$OUTPUT_FILE"
    exit 1
fi

# Extract models array (OpenAI-compatible endpoint uses .data)
model_count=$(echo "$response" | jq '(.data // []) | length')

echo "**Total Models:** $model_count" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "## Model List" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

if [ "$model_count" -eq 0 ]; then
    echo "No models available." >> "$OUTPUT_FILE"
    echo "Report generated: $OUTPUT_FILE"
    exit 0
fi

# Table header
echo "| ID | Provider | Created |" >> "$OUTPUT_FILE"
echo "|----|----------|---------|" >> "$OUTPUT_FILE"

# Format rows with jq (Unix timestamps → human-readable dates)
echo "$response" | jq -r '.data[] | "| \(.id // "N/A") | \(.owned_by // "N/A") | \(.created // 0 | tostring | strptime("%s") | strftime("%Y-%m-%d %H:%M:%S")) |"' >> "$OUTPUT_FILE"

echo "" >> "$OUTPUT_FILE"
echo "*Report generated by report-models.sh*" >> "$OUTPUT_FILE"

echo "Report generated: $OUTPUT_FILE"
exit 0
