#!/bin/bash

# Generate statistics report for CPA-X service
# Collects status, resource usage, and model count

OUTPUT_DIR="."
OUTPUT_FILE="${OUTPUT_DIR}/report-stats.md"
API_ENDPOINT="http://127.0.0.1:8317/v1/models"
CONFIG_FILE="/home/raven/.cli-proxy-api/config.yaml"
TIMESTAMP=$(date -Iseconds)

echo "# CPA-X Statistics Report" > "$OUTPUT_FILE"
echo "Generated: $TIMESTAMP" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Service status
echo "## Service Status" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
if systemctl is-active --quiet cli-proxy-api; then
    echo "**Status:** Active" >> "$OUTPUT_FILE"
    # Get detailed status output
    ACTIVE_SINCE=$(systemctl show cli-proxy-api -p ActiveEnterTimestamp --value)
    UPTIME_SECONDS=$(systemctl show cli-proxy-api -p ActiveEnterTimestamp --value | xargs -I{} date -d {} +%s 2>/dev/null)
    if [ -n "$UPTIME_SECONDS" ]; then
        NOW=$(date +%s)
        UPTIME=$(( NOW - UPTIME_SECONDS ))
        UPTIME_HUMAN=$(printf "%dd %02dh %02dm %02ds" $((UPTIME/86400)) $((UPTIME%86400/3600)) $((UPTIME%3600/60)) $((UPTIME%60)))
        echo "**Uptime:** $UPTIME_HUMAN" >> "$OUTPUT_FILE"
    fi
    PID=$(systemctl show cli-proxy-api -p MainPID --value)
    echo "**Main PID:** $PID" >> "$OUTPUT_FILE"
    MEMORY=$(systemctl show cli-proxy-api -p MemoryCurrent --value)
    if [ -n "$MEMORY" ] && [ "$MEMORY" != "0" ]; then
        MEM_MB=$(awk "BEGIN {printf \"%.1f MB\", $MEMORY/1024/1024}")
        echo "**Memory:** $MEM_MB" >> "$OUTPUT_FILE"
    fi
    # CPU usage (total, not instantaneous)
    CPU=$(systemctl show cli-proxy-api -p CPUUsageNS --value 2>/dev/null)
    if [ -n "$CPU" ] && [ "$CPU" -gt 0 ]; then
        CPU_SEC=$(awk "BEGIN {printf \"%.2f\", $CPU/1000000000}")
        echo "**CPU Time:** ${CPU_SEC}s" >> "$OUTPUT_FILE"
    fi
else
    echo "**Status:** Inactive" >> "$OUTPUT_FILE"
fi
echo "" >> "$OUTPUT_FILE"

# Model count
echo "## Models" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Extract API key
if [ -f "$CONFIG_FILE" ]; then
    API_KEY=$(grep -A 10 'api-keys:' "$CONFIG_FILE" | grep -E '^\s*-\s*sk-' | head -1 | sed -E 's/^\s*-\s*//')
    if [ -z "$API_KEY" ]; then
        API_KEY="dashboard-key-2026"
    fi
else
    API_KEY="dashboard-key-2026"
fi

response=$(curl -s -H "Authorization: Bearer $API_KEY" "$API_ENDPOINT") 2>/dev/null
model_count=$(echo "$response" | jq -r '.data // [] | length' 2>/dev/null || echo "N/A")
echo "**Total Models:** $model_count" >> "$OUTPUT_FILE"

# Extract provider distribution if available
if [ "$model_count" != "N/A" ] && [ "$model_count" -gt 0 ]; then
    echo "" >> "$OUTPUT_FILE"
    echo "### Models by Provider" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "| Provider | Count |" >> "$OUTPUT_FILE"
    echo "|----------|-------|" >> "$OUTPUT_FILE"
    echo "$response" | jq -r '.data[] | .owned_by' | sort | uniq -c | sort -nr | while read -r count provider; do
        echo "| $provider | $count |" >> "$OUTPUT_FILE"
    done
fi

echo "" >> "$OUTPUT_FILE"
echo "*Report generated by report-stats.sh*" >> "$OUTPUT_FILE"

echo "Report generated: $OUTPUT_FILE"
exit 0
